### PR TITLE
Add `hasSufficientPermission` implementation

### PR DESCRIPTION
**Pull request by vdusart**
Here is an implementation of the `hasSufficientPermission`

### CODE REVIEW

**Comment by vdusart** [comment]
What do you think to convert this:
```solidity
if (!opt.permissionRequire(_required, opt.permissionOf(msg.sender)) {
```

by this:
```solidity
if (!opt.hasSufficientPermission(msg.sender, msg.sender, _required)) {
```
On one hand it's clearer to use this function to check if someone has enough rights (and still the fact that you have to put `msg.sender` as the owner may seem weird and confusing) but on the other hand doing the delegated permissions checks costs extra gas.

I don't think it's a good idea but it's worth mentioning.

**Comment by vdusart** [comment]
One more thing is the fact that permissions are transferable.
In your `AEcosystem` exemple you are doing a check on whether a user is blacklisted or not ([here](https://github.com/orochi-network/EIP-6366/blob/main/contracts/example/AEcosystem.sol#L26))
But that means that once a person is blacklisted they can transfer their `PERMISSION_DENIED` token to someone else (unless I'm wrong).
To avoid that case, maybe we should overload the transfer function so that it also has the `denyOwner` modifier on it.

**Comment by chiro-hiro** [comment]
> Here is an implementation of the hasSufficientPermission

Could we change the method name from `hasSufficientPermission()` to `hasPermission()`.  It still mean the same, just shorter.

**Comment by chiro-hiro** [comment]
> One more thing is the fact that permissions are transferable. In your `AEcosystem` exemple you are doing a check on whether a user is blacklisted or not ([here](https://github.com/orochi-network/EIP-6366/blob/main/contracts/example/AEcosystem.sol#L26)) But that means that once a person is blacklisted they can transfer their `PERMISSION_DENIED` token to someone else (unless I'm wrong). To avoid that case, maybe we should overload the transfer function so that it also has the `denyOwner` modifier on it.

Cool, I was missed that case.

**Pull request merged**
